(async function(){
  const host=document.querySelector('#build-guide'),id=document.body.dataset.buildId;let data,itemData,aspectData,paragonData,warPlanData,runeStageData;
  try{[data,itemData,aspectData,paragonData,warPlanData,runeStageData]=await Promise.all([DiabloSite.loadJson('data/builds.json'),DiabloSite.loadJson('data/items.json'),DiabloSite.loadJson('data/aspects.json'),DiabloSite.loadJson('data/paragon/whirlwind-board-geometry.json'),DiabloSite.loadJson('data/war-plans.json'),DiabloSite.loadJson('data/rune-stages.json'),DiabloSite.loadAssets()])}catch(error){host.innerHTML=`<p class="empty-state">${error.message}</p>`;return}
  const build=data.builds.find(b=>b.id===id);if(!build){host.innerHTML='<p class="empty-state">Build not found.</p>';return}
  const variantStorageKey=`diablo-build-variant:${build.id}`;
  let selected=build.defaultVariant,sectionObserver;
  try{const savedVariant=localStorage.getItem(variantStorageKey);if(savedVariant&&build.variants[savedVariant])selected=savedVariant}catch{}
  const esc=DiabloSite.escapeHtml;
  const icon=(assetId,label)=>`<span class="icon-tile" aria-hidden="true">${DiabloSite.assetMarkup(assetId,{alt:''})}</span>`;
  const assetKey=value=>(value||'').normalize('NFKD').replace(/[’']/g,'').replace(/[^a-zA-Z0-9]+/g,'-').replace(/^-|-$/g,'').toLowerCase();
  const rarityKey=item=>assetKey(item.rarity);
  const gearIcon=item=>`<span class="icon-tile gear-icon"${item.rarity?` data-rarity="${esc(rarityKey(item))}"`:''}>${DiabloSite.assetMarkup(item.assetId||`item:${assetKey(item.name)}`,{alt:''})}</span>`;
  const equipmentName=(item)=>item.rarity==='Legendary'?(item.aspect||'Flexible Aspect Slot'):item.name;
  const equipmentButton=(item,index)=>{const rarity=esc(rarityKey(item));return `<button class="equipment-slot" type="button" data-equipment-index="${index}">${gearIcon(item)}<span><span class="slot-label">${esc(item.slot)}</span><strong class="item-name" data-rarity="${rarity}">${esc(equipmentName(item))}</strong></span></button>`};
  const completionKey=(variant,slot)=>`diablo-equipment-complete:${build.id}:${variant}:${assetKey(slot)}`;
  const equipmentComplete=slot=>{try{return localStorage.getItem(completionKey(selected,slot))==='1'}catch{return false}};
  const equipmentRow=(item,index,side)=>{const complete=equipmentComplete(item.slot),toggle=`<button class="equipment-complete-toggle" type="button" data-equipment-complete="${esc(item.slot)}" aria-pressed="${complete}" aria-label="Mark ${esc(item.slot)} as ${complete?'incomplete':'equipped and fully optimized'}"><span aria-hidden="true">✓</span></button>`;return `<div class="equipment-row equipment-row-${side}${complete?' is-complete':''}">${side==='left'?toggle:''}${equipmentButton(item,index)}${side==='right'?toggle:''}</div>`};
  const itemDetails=item=>{const unique=itemData.items[item.assetId],legendaryPower=item.aspect&&aspectData.aspects[assetKey(item.aspect)]?.power,greater=new Set(item.greaterAffixes||[]),affixBlock=`<div class="recommended-affixes"><h3>Best affixes, in order</h3><ol>${item.affixes.map(x=>`<li${greater.has(x)?' class="greater-affix"':''}>${greater.has(x)?'<span aria-label="Greater Affix" title="Greater Affix">✷</span> ':''}${esc(x)}</li>`).join('')}</ol>${greater.size?'<p class="affix-legend"><span aria-hidden="true">✷</span> Masterworked Item</p>':''}</div>`,detailBlock=`${unique?`<div class="unique-power"><h3>Unique power</h3><p>${esc(unique.uniquePower)}</p></div>`:''}${legendaryPower?`<div class="legendary-power"><h3>Legendary power</h3><p>${esc(legendaryPower)}</p></div>`:''}${affixBlock}`;return `<div class="item-popup-heading">${gearIcon(item)}<div><span class="slot-label">${esc(item.slot)}</span><strong id="item-dialog-title" class="item-name" data-rarity="${esc(item.rarity.toLowerCase().replace(/\s+/g,'-'))}">${esc(equipmentName(item))}</strong> <span class="rarity" data-rarity="${esc(item.rarity.toLowerCase().replace(/\s+/g,'-'))}">${esc(item.rarity)}</span></div></div><div class="equipment-body">${detailBlock}<div><h3>Crafting targets</h3><p><strong>Temper:</strong> ${esc(item.temper||'Not applicable')}</p><p><strong>Masterwork:</strong> ${esc(item.masterwork||'Not applicable')}</p>${item.aspect?`<p><strong>Aspect:</strong> ${esc(item.aspect)}</p>`:''}</div></div>`};
  const aspectDetails=(entry,item)=>{const aspectItem={name:entry.name,slot:item?.slot||'Aspect',rarity:'Legendary',aspect:entry.name,assetId:`aspect:${assetKey(entry.name)}`};const description=entry.description||aspectData.aspects[assetKey(entry.name)]?.power||'Exact effect text is not yet recorded for this build variant. Verify the in-game tooltip before imprinting.';return `<div class="item-popup-heading">${gearIcon(aspectItem)}<div><span class="slot-label">Legendary Aspect</span><strong id="item-dialog-title" class="item-name" data-rarity="legendary">${esc(entry.name)}</strong></div></div><div class="aspect-popup-body"><h3>Legendary power</h3><p>${esc(description)}</p>${item?.slot?`<p class="meta">Assigned slot: ${esc(item.slot)}</p>`:''}</div>`};
  const talismanMembers=items=>items.flatMap(item=>{
    if(!/5 pieces/i.test(item.type))return [item];
    const set=/sescheron/i.test(item.name)?"Sescheron's Fury":"the Crucible";
    return ['Phoba','Mlor','Linta','Fer','Berú'].map(name=>{const fullName=`${name} of ${set}`;return{type:'Set Charm',name:fullName,role:item.role,rarity:'Set Charm',assetId:`talisman:${assetKey(fullName)}`}});
  });
  const variantFor=(key,seen=new Set())=>{
    const raw=build.variants[key];
    if(!raw||!raw.extends||seen.has(key))return raw;
    seen.add(key);
    return {...variantFor(raw.extends,seen),...raw};
  };
  const sectionId=title=>title.toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
  const sectionTitles=['Equipment','Talismans, Charms & Seal','Weapon/Class Mechanic','Runes & Seasonal Systems','Skills','Paragon Board','Mercenary','War Plans'];
  function section(title,content){return `<section class="panel guide-section" id="${sectionId(title)}"><h2>${title}</h2>${content}</section>`}
  const modifierName=modifier=>typeof modifier==='string'?modifier:modifier.name;
  const modifierSource=modifier=>typeof modifier==='string'?'leveling':modifier.source;
  const runeStageItem=item=>`<article class="rune-stage-item"><span class="rune-stage-icon"><img src="${esc(item.image)}" alt="" loading="lazy" decoding="async" fetchpriority="low"></span><strong>${esc(item.name)}</strong></article>`;
  const runeStagesMarkup=()=>`<div class="rune-stage-viewer"><div class="rune-stage-tabs" role="tablist" aria-label="Rune and Soul Splinter progression">${runeStageData.stages.map((stage,index)=>`<button type="button" role="tab" data-rune-stage="${esc(stage.id)}" aria-selected="${index===0}" aria-controls="rune-stage-${esc(stage.id)}">${esc(stage.label)}</button>`).join('')}</div>${runeStageData.stages.map((stage,index)=>`<div class="rune-stage-panel${index===0?' is-active':''}" id="rune-stage-${esc(stage.id)}" data-rune-stage-panel="${esc(stage.id)}" role="tabpanel"${index===0?'':' hidden'}><h3>Rune pairs</h3><div class="rune-stage-pairs">${stage.pairs.map(pair=>`<div class="rune-stage-pair">${runeStageItem(pair[0])}<span class="rune-pair-connector" aria-hidden="true"></span>${runeStageItem(pair[1])}</div>`).join('')}</div><h3>Soul Splinters</h3><div class="soul-stage-row">${runeStageData.soulSplinters.map(runeStageItem).join('')}</div></div>`).join('')}</div>`;
  function render(){const v=variantFor(selected),mercenary=build.mercenarySetup.mercenary,reinforcement=build.mercenarySetup.reinforcement,explicitPriority=build.variants[selected].equipmentPriority||[],priorityRecords=explicitPriority.map(entry=>{const item=v.equipment.find(candidate=>assetKey(candidate.name)===assetKey(entry.name)||assetKey(candidate.aspect)===assetKey(entry.name));return{entry,item,isAspect:Boolean(item?.aspect&&assetKey(item.aspect)===assetKey(entry.name))||/aspect/i.test(entry.name)}});sectionObserver?.disconnect();host.innerHTML=`
    <section class="panel build-header" id="build-top"><div class="build-title-row"><div><p class="eyebrow">${esc(build.class)} · ${esc(build.patchLabel)}</p><h1>${esc(build.name)}</h1></div></div></section>
    <div class="build-guide-layout"><div class="guide-sidebar"><aside class="panel guide-toc" aria-labelledby="toc-heading"><h2 id="toc-heading">Table of Contents</h2><ol>${sectionTitles.map(title=>`<li><a href="#${sectionId(title)}">${title}</a></li>`).join('')}</ol></aside>${build.variantOrder.length>1?`<section class="panel sidebar-variants" aria-labelledby="variant-heading"><h2 id="variant-heading">Variant</h2><div class="variant-tabs" role="tablist" aria-label="Build variant">${build.variantOrder.map(key=>`<button class="variant-button" role="tab" type="button" data-variant="${key}" aria-selected="${key===selected}">${esc(build.variants[key].label)}</button>`).join('')}</div></section>`:''}<aside class="panel guide-sources" aria-labelledby="sources-heading"><h2 id="sources-heading">Sources</h2><ul><li><a href="https://maxroll.gg/d4/build-guides/whirlwind-barbarian-guide" target="_blank" rel="noopener noreferrer">Maxroll.gg</a></li><li><a href="https://mobalytics.gg/diablo-4/builds/barbarian-whirl-wind-barb" target="_blank" rel="noopener noreferrer">Mobalytics.gg</a></li></ul></aside></div><div class="build-guide-content">
    ${section('Equipment',`<div class="equipment-showcase"><div class="equipment-column">${v.equipment.map((item,index)=>({item,index})).filter(({item})=>!['Amulet','Ring 1','Ring 2','2H Slashing','Dual Wield 2'].includes(item.slot)).map(({item,index})=>equipmentRow(item,index,'left')).join('')}</div><div class="equipment-column equipment-column-right">${v.equipment.map((item,index)=>({item,index})).filter(({item})=>['Amulet','Ring 1','Ring 2','2H Slashing','Dual Wield 2'].includes(item.slot)).map(({item,index})=>equipmentRow(item,index,'right')).join('')}</div></div><div class="equipment-priority-strip"><h3>Equipment Priority</h3>${priorityRecords.length?`<div class="priority-icons">${priorityRecords.map(({entry,item,isAspect},index)=>`<button class="priority-icon" type="button" data-priority-index="${index}" aria-label="${index+1}. ${esc(entry.name)}" title="${index+1}. ${esc(entry.name)}">${gearIcon(isAspect?{name:entry.name,slot:'Aspect',rarity:'Legendary',aspect:entry.name,assetId:`aspect:${assetKey(entry.name)}`}:(item||entry))}</button>`).join('')}</div>`:'<p class="meta">Priority order has not yet been recorded for this variant.</p>'}</div>`)}
    ${section('Talismans, Charms & Seal',`<div class="talisman-showcase">${talismanMembers(v.talismans).map((x,index)=>`<button class="talisman-slot" type="button" data-talisman-index="${index}">${gearIcon(x,'talisman')}<span><strong>${esc(x.name)}</strong><small>${esc(x.type)}</small></span></button>`).join('')}</div>`)}
    ${section('Weapon/Class Mechanic',`<div class="system-grid">${v.expertise.map(x=>`<article class="system-card system-card-with-icon">${icon(x.assetId,x.name)}<div><h3>${esc(x.type)}</h3><strong>${esc(x.name)}</strong><p>${esc(x.assignment)}</p></div></article>`).join('')}</div>`)}
    ${section('Runes & Seasonal Systems',runeStagesMarkup())}
    ${section('Skills',`${v.skillPointSources?`<div class="skill-source-summary"><div><strong>${v.skillPointSources.leveling}</strong><span>Leveling points</span><small>Earned by reaching level 70</small></div><div class="seasonal-points"><strong>+${v.skillPointSources.seasonal}</strong><span>${esc(v.skillPointSources.seasonalLabel)}</span><small>Complete seasonal progression when ready</small></div><div><strong>${v.skillPointSources.total}</strong><span>Complete build</span><small>Eternal: extras come from ${esc(v.skillPointSources.eternalLabel)}</small></div></div>`:''}<p class="warning"><strong>Spend the leveling points first.</strong> Gold “Season” labels identify allocations that can wait until their Season Rank / Journey points are unlocked.</p><div class="skill-grid">${v.skills.map(x=>`<article class="skill-card"><div class="skill-card-heading">${icon(x.skillId,x.name)}<div><div class="skill-points">${x.manualPoints}/${x.maxManualPoints}</div><strong>${esc(x.name)}</strong></div>${x.seasonPoints?`<span class="skill-source-badge">${x.seasonPoints} Season</span>`:''}</div><p>${esc(x.kind)}</p>${x.levelPoints!==undefined?`<div class="skill-allocation"><span>${x.levelPoints} leveling${x.seasonPoints?` + ${x.seasonPoints} seasonal`:''} ranks</span></div>`:''}${x.modifiers.length?`<ul class="skill-modifiers">${x.modifiers.map(modifier=>`<li>${esc(modifierName(modifier))}${modifierSource(modifier)==='season'?'<span class="skill-source-badge">Season</span>':''}</li>`).join('')}</ul>`:''}</article>`).join('')}</div><p class="verification-note">${esc(v.skillVerification)}</p>`)}
    ${section('Paragon Board',ParagonBoardUI.sectionMarkup(paragonData,v.label,paragonData.variantKey!==selected))}
    ${section('Mercenary',`<div class="people-grid mercenary-grid"><article class="person-card mercenary-card"><div class="person-heading">${icon(mercenary.assetId,mercenary.name)}<div><span class="slot-label">${esc(mercenary.role)}</span><strong>${esc(mercenary.name)}</strong></div></div><div class="mercenary-selections">${mercenary.selections.map(selection=>`<div>${icon(selection.assetId,selection.name)}<span>${esc(selection.type)}</span><strong>${esc(selection.name)}</strong></div>`).join('')}</div></article><article class="person-card mercenary-card"><div class="person-heading">${icon(reinforcement.assetId,reinforcement.name)}<div><span class="slot-label">${esc(reinforcement.role)}</span><strong>${esc(reinforcement.name)}</strong></div></div><div class="mercenary-selections"><div>${icon(reinforcement.skillAssetId,reinforcement.skill)}<span>Reinforcement Skill</span><strong>${esc(reinforcement.skill)}</strong></div><div><span>Opportunity</span><strong>${esc(reinforcement.opportunity)}</strong></div></div><p>${esc(reinforcement.effect)}</p></article></div>`)}
    ${section('War Plans',WarPlansUI.sectionMarkup(warPlanData))}
    </div></div><dialog class="item-dialog" aria-labelledby="item-dialog-title"><button class="item-dialog-close" type="button" aria-label="Close item details">×</button><div class="item-dialog-content"></div></dialog>
  `;
    host.querySelectorAll('[data-variant]').forEach(button=>button.addEventListener('click',()=>{selected=button.dataset.variant;try{localStorage.setItem(variantStorageKey,selected)}catch{}render()}));
    host.querySelectorAll('[data-equipment-complete]').forEach(button=>button.addEventListener('click',()=>{const complete=button.getAttribute('aria-pressed')!=='true',slot=button.dataset.equipmentComplete;button.setAttribute('aria-pressed',String(complete));button.setAttribute('aria-label',`Mark ${slot} as ${complete?'incomplete':'equipped and fully optimized'}`);button.closest('.equipment-row').classList.toggle('is-complete',complete);try{if(complete)localStorage.setItem(completionKey(selected,slot),'1');else localStorage.removeItem(completionKey(selected,slot))}catch{}}));
    const dialog=host.querySelector('.item-dialog'),dialogContent=host.querySelector('.item-dialog-content');
    const hoverPreview=matchMedia('(hover:hover) and (pointer:fine)').matches;
    const positionPreview=button=>{const box=button.getBoundingClientRect(),width=Math.min(520,innerWidth-32);dialog.style.width=`${width}px`;const left=box.left+box.width/2<innerWidth/2?Math.min(box.right+14,innerWidth-width-16):Math.max(16,box.left-width-14);dialog.style.left=`${left}px`;dialog.style.top=`${Math.max(16,Math.min(box.top,innerHeight-dialog.offsetHeight-16))}px`};
    host.querySelectorAll('[data-equipment-index]').forEach(button=>{
      const show=()=>{if(dialog.open)dialog.close();dialogContent.innerHTML=itemDetails(v.equipment[Number(button.dataset.equipmentIndex)]);dialog.show();requestAnimationFrame(()=>positionPreview(button))};
      if(hoverPreview){button.addEventListener('mouseenter',show);button.addEventListener('mouseleave',()=>dialog.close());button.addEventListener('focus',show);button.addEventListener('blur',()=>dialog.close())}
      else button.addEventListener('click',()=>{dialogContent.innerHTML=itemDetails(v.equipment[Number(button.dataset.equipmentIndex)]);dialog.showModal()});
    });
    host.querySelectorAll('[data-priority-index]').forEach(button=>{
      const record=priorityRecords[Number(button.dataset.priorityIndex)];
      const details=()=>record.isAspect?aspectDetails(record.entry,record.item):record.item?itemDetails(record.item):`<div class="item-popup-heading">${gearIcon(record.entry)}<div><span class="slot-label">Equipment</span><strong id="item-dialog-title">${esc(record.entry.name)}</strong></div></div><div class="aspect-popup-body"><p>Equipment details have not yet been recorded for this variant.</p></div>`;
      const show=()=>{if(dialog.open)dialog.close();dialogContent.innerHTML=details();if(hoverPreview){dialog.show();requestAnimationFrame(()=>positionPreview(button))}else dialog.showModal()};
      if(hoverPreview){button.addEventListener('mouseenter',show);button.addEventListener('mouseleave',()=>dialog.close());button.addEventListener('focus',show);button.addEventListener('blur',()=>dialog.close())}
      else button.addEventListener('click',show);
    });
    const expandedTalismans=talismanMembers(v.talismans);
    host.querySelectorAll('[data-talisman-index]').forEach(button=>{
      const show=()=>{if(dialog.open)dialog.close();const item=expandedTalismans[Number(button.dataset.talismanIndex)];dialogContent.innerHTML=`<div class="item-popup-heading">${gearIcon(item,'talisman')}<div><span class="slot-label">${esc(item.type)}</span><strong id="item-dialog-title">${esc(item.name)}</strong></div></div><div class="talisman-popup-body"><h3>Build role</h3><p>${esc(item.role||'Use this charm in the selected variant.')}</p></div>`;if(hoverPreview){dialog.show();requestAnimationFrame(()=>positionPreview(button))}else dialog.showModal()};
      if(hoverPreview){button.addEventListener('mouseenter',show);button.addEventListener('mouseleave',()=>dialog.close());button.addEventListener('focus',show);button.addEventListener('blur',()=>dialog.close())}
      else button.addEventListener('click',show);
    });
    host.querySelector('.item-dialog-close').addEventListener('click',()=>dialog.close());
    dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});
    host.querySelectorAll('[data-rune-stage]').forEach(button=>button.addEventListener('click',()=>{
      const stage=button.dataset.runeStage;
      host.querySelectorAll('[data-rune-stage]').forEach(tab=>tab.setAttribute('aria-selected',String(tab===button)));
      host.querySelectorAll('[data-rune-stage-panel]').forEach(panel=>{const active=panel.dataset.runeStagePanel===stage;panel.classList.toggle('is-active',active);panel.hidden=!active});
    }));
    ParagonBoardUI.mount(host.querySelector('[data-paragon-section]'),paragonData);
    WarPlansUI.mount(host.querySelector('[data-war-plan-viewer]'),warPlanData);
    const tocLinks=[...host.querySelectorAll('.guide-toc a')];
    const markCurrent=id=>tocLinks.forEach(link=>link.toggleAttribute('aria-current',link.hash===`#${id}`));
    markCurrent(sectionId(sectionTitles[0]));
    sectionObserver=new IntersectionObserver(entries=>{
      const current=entries.filter(entry=>entry.isIntersecting).sort((a,b)=>a.boundingClientRect.top-b.boundingClientRect.top)[0];
      if(current)markCurrent(current.target.id);
    },{rootMargin:'-96px 0px -65% 0px',threshold:0});
    host.querySelectorAll('.guide-section').forEach(item=>sectionObserver.observe(item));
  }
  render();
})();
