<?php
declare(strict_types=1);require __DIR__.'/../../account-app/bootstrap.php';$admin=requireSuperAdmin();$message='';$error='';
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
  requireAccountCsrf();$targetId=(int)($_POST['user_id']??0);$role=in_array($_POST['role']??'', ['user','super_admin'],true)?$_POST['role']:'user';$active=isset($_POST['is_active'])?1:0;
  if($targetId===(int)$admin['id']&&($role!=='super_admin'||!$active))$error='You cannot disable or demote your own super-administrator account.';
  else{$target=db()->prepare('UPDATE users SET role=?,is_active=? WHERE id=?');$target->execute([$role,$active,$targetId]);$apps=db()->query('SELECT id,application_key FROM applications WHERE is_active=1')->fetchAll();$delete=db()->prepare('DELETE FROM user_application_access WHERE user_id=?');$delete->execute([$targetId]);$insert=db()->prepare('INSERT INTO user_application_access(user_id,application_id,access_level) VALUES (?,?,?)');foreach($apps as $app){$level=$_POST['access'][$app['application_key']]??'';if(in_array($level,['user','manager','admin'],true))$insert->execute([$targetId,$app['id'],$level]);}db()->prepare("INSERT INTO admin_audit_log(admin_user_id,action,target_type,target_id,details) VALUES (?,'user_access_updated','user',?,?)")->execute([$admin['id'],(string)$targetId,json_encode(['role'=>$role,'active'=>$active,'access'=>$_POST['access']??[]])]);$message='User access updated.';}
}
$apps=db()->query('SELECT id,application_key,display_name FROM applications WHERE is_active=1 ORDER BY display_name')->fetchAll();$users=db()->query('SELECT id,username,display_name,role,is_active,created_at,last_login_at FROM users ORDER BY created_at')->fetchAll();$accessRows=db()->query('SELECT user_id,application_id,access_level FROM user_application_access')->fetchAll();$access=[];foreach($accessRows as $row)$access[$row['user_id']][$row['application_id']]=$row['access_level'];renderAccountHeader('Users & Access');?>
<section class="card"><h1>Users &amp; Access</h1><p class="muted">Super administrators have access to every application. Other accounts receive only the permissions selected here.</p><?php if($message):?><p class="success"><?=h($message)?></p><?php endif?><?php if($error):?><p class="error"><?=h($error)?></p><?php endif?></section>
<?php foreach($users as $user):?><section class="card"><form method="post"><input type="hidden" name="csrf_token" value="<?=h(accountCsrf())?>"><input type="hidden" name="user_id" value="<?=$user['id']?>"><h2><?=h($user['display_name'])?> <small class="muted">@<?=h($user['username'])?></small></h2><p class="muted">Created <?=h($user['created_at'])?> · Last login <?=h($user['last_login_at']??'Never')?></p><div class="grid"><label class="field">Global role<select name="role"><option value="user" <?=$user['role']==='user'?'selected':''?>>User</option><option value="super_admin" <?=$user['role']==='super_admin'?'selected':''?>>Super administrator</option></select></label><label class="field">Account status<span><input style="width:auto" type="checkbox" name="is_active" value="1" <?=$user['is_active']?'checked':''?>> Active</span></label><?php foreach($apps as $app):$level=$access[$user['id']][$app['id']]??'';?><label class="field"><?=h($app['display_name'])?><select name="access[<?=h($app['application_key'])?>]"><option value="">No access</option><option value="user" <?=$level==='user'?'selected':''?>>User</option><option value="manager" <?=$level==='manager'?'selected':''?>>Manager</option><option value="admin" <?=$level==='admin'?'selected':''?>>Administrator</option></select></label><?php endforeach?></div><button>Save user</button></form></section><?php endforeach?>
<?php renderAccountFooter();
